In [1]:
import numpy as np

In [2]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
np.random.rand(3,3)

array([[0.37427293, 0.4597915 , 0.70845228],
       [0.38090895, 0.62443994, 0.52931518],
       [0.36086908, 0.11812417, 0.41742201]])

In [9]:
aar = np.arange(25)

In [11]:
aar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:

ranarr = np.random.randint(0,50,10)


In [13]:
ranarr.min()

2

In [14]:
ranarr.max()

45

In [15]:
ranarr.argmax()

6

In [16]:
ranarr

array([18, 32, 35, 27, 42, 44, 45,  2, 36, 20])

In [18]:
aar.shape

(25,)

In [19]:
tt1 = np.random.randint(0,10,5)

In [20]:
tt2 = np.random.randint(0,10,5)

In [21]:
tt1

array([1, 4, 5, 6, 5])

In [22]:
tt2

array([2, 7, 8, 6, 9])

In [23]:
tt3 = tt1*tt2

In [24]:
tt3

array([ 2, 28, 40, 36, 45])

In [25]:
m1 = np.random.randint(0,10,9)
m2 = np.random.randint(0,10,9)


In [26]:
m1

array([5, 0, 8, 4, 8, 4, 0, 9, 0])

In [27]:
m2

array([9, 2, 1, 5, 8, 9, 2, 6, 5])

In [28]:
m1 = m1.reshape(3,3)
m2 = m2.reshape(3,3)

In [29]:
m1

array([[5, 0, 8],
       [4, 8, 4],
       [0, 9, 0]])

In [30]:
m2

array([[9, 2, 1],
       [5, 8, 9],
       [2, 6, 5]])

In [31]:
m3 = m1*m2

In [32]:
m3

array([[45,  0,  8],
       [20, 64, 36],
       [ 0, 54,  0]])

In [34]:
m3[0,0]

45

In [35]:
m3 > 20

array([[ True, False, False],
       [False,  True,  True],
       [False,  True, False]])

In [36]:
m3[m3 >20]

array([45, 64, 36, 54])

In [37]:
m3*3

array([[135,   0,  24],
       [ 60, 192, 108],
       [  0, 162,   0]])